---
name: checks

on:
  push:
    branches: [master]

jobs:
  markdown-link-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: gaurav-nelson/github-action-markdown-link-check@0.4.0

  markdownlint-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          config_file: .markdownlint.yml

  markdown-spell-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install markdown-spellcheck
        run: npm install -g markdown-spellcheck

      - name: Run mdspell
        run: find . -type f -name "*.md" -exec mdspell --ignore-numbers --ignore-acronyms --report --en-gb {} \;

  checks:
    name: Molecule checks
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        env:
          - MOLECULE_DISTRO: centos7

    steps:
      - uses: actions/checkout@v2

      - name: Update repositories
        run: sudo apt update

      - name: Install Setuptools
        run: sudo apt-get install -y python3-setuptools

      - name: Install test dependencies
        run: sudo -H pip3 install molecule docker

      - name: Run tests
        run: molecule test
